### ISSUE TITLE
Incorrect REQUESTED-ADDRESS-FAMILY attribute length

### ISSUE THREAD

**Issue by weiss** [firefart/stunner#12]
stunner sets the length of the `REQUESTED-ADDRESS-FAMILY` attribute to 1 byte, whereas the "length of this attribute is 4 bytes" as [per RFC 6256][1] (just as for e.g. `REQUESTED-TRANSPORT`, which does have the correct length):

![image](https://user-images.githubusercontent.com/71850/178285656-d9678e7b-cd84-44fd-84fb-c8039159f9cb.png)

(Wireshark calls it `REQUESTED-ADDRESS-TYPE`, as that was the [initial name][2] for attribute `0x0017`.)

At least [eturnal][3] rejects requests for this reason (because "be strict in what you accept").

Many thanks for this great tool!

[1]: https://www.rfc-editor.org/rfc/rfc6156.html#section-4.1.1
[2]: https://datatracker.ietf.org/doc/html/draft-ietf-behave-turn-ipv6-03
[3]: https://eturnal.net

**Comment by firefart** [comment]
@weiss good catch thanks! I currently have no IPv6 enabled turn server at hand for testing but pushed a quick fix to the main branch. Can you please test if this now works with eturnal ?

**Comment by firefart** [comment]
Jeah the RFC is not clear about this whether the length value should include the reserved bytes or not, wireshark decodes it correctly but that does not mean anything :)
This page https://docs.microsoft.com/en-us/openspecs/office_protocols/ms-turn/e7efc457-9312-4a6b-8089-94032a599198 means to always set the length to `0x0004` so will try that

**Comment by weiss** [comment]
> Jeah the RFC is not clear about this whether the length value should include the reserved bytes or not, 

I think the answer is "yes it should include them", it's one byte payload plus three reserved bytes, no?

> always set the length to `0x0004` so will try that

Yes I'm pretty sure that's what the RFC is trying to say as well.  Wireshark and other servers can obviously decode things just fine by accepting other lengths (as long as they match reality), I'm just [deliberately][1] picky in eturnal.

> can you please try again?

Works just fine now, thank you very much for the super-quick fix! :+1: 

[1]: https://tools.ietf.org/id/draft-thomson-postel-was-wrong-03.html

**Comment by firefart** [comment]
Thanks! Uploaded version v0.4.0 with this fix:
https://github.com/firefart/stunner/releases/tag/v0.4.0

thanks again for the report!
