### ISSUE TITLE
adding 192.88.99.0/24 to range-scan command?

### ISSUE THREAD

**Issue by gl4nce** [firefart/stunner#17]
According to [this configuration example](https://matrix-org.github.io/synapse/latest/turn-howto.html#configuration) with blocked private and multicast addresses, maybe it's a good idea to add `192.88.99.1` and `192.88.99.254` to range-scan command?

**Comment by firefart** [comment]
This IP block is owned by Hurricane: https://ipinfo.io/AS6939/192.88.99.0/24

I guess the tutorial you read uses some services from them and this is the range they provide it in, but this is nothing private that's not routed on the internet

**Comment by gl4nce** [comment]
Thanks for your explanation. You are right. Sorry for disturbing. My fault.
Awesome tool by the way. Love it !
