### ISSUE TITLE
it does not work with google server

### ISSUE THREAD

**Issue by Zibri** [firefart/stunner#19]
`stunner socks -s 74.125.247.128:3478 -u "username" -p "password"`

upon a socks5 request:

```
time="2022-12-28T18:50:01+02:00" level=info msg="starting SOCKS server on 127.0.0.1:1080"
time="2022-12-28T18:50:06+02:00" level=info msg="Connecting to 104.26.1.100:443"
time="2022-12-28T18:50:06+02:00" level=error msg="socks error: error on allocate response: Error 442: "
```

**Comment by firefart** [comment]
error 442 is "unsupported transport protocol" so it does not support tcp.

From the RFC:
```text
442  (Unsupported Transport Protocol): The Allocate request asked the
	server to use a transport protocol between the server and the peer
	that the server does not support.  NOTE: This does NOT refer to
	the transport protocol used in the 5-tuple.
```

**Comment by Zibri** [comment]
Why did you close this? Can you explain why this happens?

**Comment by Zibri** [comment]
> error 442 is "unsupported transport protocol" so it does not support tcp.

Google turn server supports both TCP and UDP.

**Comment by firefart** [comment]
that’s the error returned by the server

**Comment by Zibri** [comment]
> that’s the error returned by the server

yes. but I don't know why.
