### ISSUE TITLE
stunner fails with udp and tls with coturn

### ISSUE THREAD

**Issue by dennisTGC** [firefart/stunner#20]
Hi, 

great util, makes troubleshooting stun/turn way easier. But I see different results when I'm using 
```
./stunner info -s server.domain.tld:443 --protocol udp --tls
```
without the `--tls` it succeeds, so I don't think its a firewall issue. But with the `--tls` I'm getting an error that the server doesn't not support stun/udp/tcp. But if I connect my Nextcloud Talk instance with `turns` on udp, it says ICE is succesfull. With the protocol `tcp` I also don't have any issues.

I'm using coturn v4.5.2-3.1, they seem to be confirming to the RFC's:
https://github.com/coturn/coturn/blob/master/README.md

Can you elaborate on this?

**Comment by firefart** [comment]
Thanks! DTLS support was missing for udp and should be working now

**Comment by dennisTGC** [comment]
thank you!
