### ISSUE TITLE
Installation on Kali 

### ISSUE THREAD

**Issue by Ctrlcer** [firefart/stunner#21]
Hi, I'm a student doing my ethical hacking thesis. 
I'm wondering how can I install this amazing tool on my kali?
Thanks!!!

**Comment by firefart** [comment]
there is an open issue to get this into kali over here
https://bugs.kali.org/view.php?id=7712

until this is done go to https://github.com/firefart/stunner/releases/latest an simply download the correct binary for your architecture and run it
