### ISSUE TITLE
Change the license to one from opensource.org

### ISSUE THREAD

**Issue by harishpillay** [firefart/stunner#3]
It does not make sense to have a CC license for software. I would suggest that a license from the Open Source Inc be considered. I would strongly encourage the GNU General Public LIcense v3 as the license.

**Comment by firefart** [comment]
Thanks but I have choosen the license on purpose so the tool is not used or reselled in commercial tools without prior approval.

**Comment by harishpillay** [comment]
Sure, it is your choice.
