### ISSUE TITLE
I don't know what's wrong

### ISSUE THREAD

**Issue by Zibri** [firefart/stunner#31]
From one command prompt I do:

`C:\>stunner socks -s "142.250.82.249:3478" -u "CNr2yKYGEgYsM4ipwOgY5vz/h7MLIICjBTAB" -p "PvR81fQZhd6kwAhNZDPre5YJSo8=" -x
`
from another shell I do:
`curl -x socks5h://localhost:1080 https://www.google.com
`

On the first shell I get:
```
time="2023-08-07T16:26:43+03:00" level=info msg="starting SOCKS server on 127.0.0.1:1080"
time="2023-08-07T16:26:46+03:00" level=info msg="Connecting to 142.250.200.228:443"
time="2023-08-07T16:26:46+03:00" level=error msg="socks error: error on allocate response: Error 442: Unsupported Transport Protocol"
```

On the second one I get:
`curl: (97) connection to proxy closed`

Am I doing something wrong?

**Comment by firefart** [comment]
the server you are testing does not support TCP connections (which are required for socks). Use the `info` to get the supported protocols and options on the server. You might only be able to test udp based services behind this server (for example with the `udp-scanner` option)
