### ISSUE TITLE
SOCKS error: immediate timeout when using TLS

### ISSUE THREAD

**Issue by livy111** [firefart/stunner#44]
when curling public page using SOCKS, TCP, and TLS, immediately times out with:
`ERRO[0034] socks error: could not cast control connection to TCPConn`

Am running default coturn server setup with basic creds and self-signed cert. Changed default TURNS port to 443, but not running a web server. This works when the -tls flag is removed, but I would like to encrypt the connection. Am using Kali linux OS. TLS certs are valid when running openssl s_client.

`./stunner socks -s 192.168.197.136:443 -u test -p password -tls -x --protocol tcp`
`proxychains curl -vk http://ipinfo.io`
Receive error:
`ERRO[0034] socks error: could not cast control connection to TCPConn`

Seems to just immediately timeout and not hold open the connection?
Wireshark snippet of above
![image](https://github.com/firefart/stunner/assets/59734923/5edd6138-cc3e-4c2c-b569-975edad1884f)

**Comment by firefart** [comment]
Hi,
can you please share your coturn config (`/etc/turnserver.conf`) so I can have a look with the exact same setting? Thanks!

**Comment by livy111** [comment]
/etc/turnserver.conf
Note that the turnzey-relay.org is just a made up name I have mapped in /etc/hosts to my turn server ip 192.168.197.136 as shown in wireshark above.
[turnserver.conf.txt](https://github.com/firefart/stunner/files/14139145/turnserver.conf.txt)

**Comment by firefart** [comment]
Thanks for the report @livy111 . I release v0.5.5 with a fix included https://github.com/firefart/stunner/releases/tag/v0.5.5
