### ISSUE TITLE
Connection refused in Test-Setup

### ISSUE THREAD

**Issue by KoEnix** [firefart/stunner#50]
Hi,
i got a problem, which i cant find the error in. I got a small test setup with coturn, and when trying to scan a ssh port lying behind the coturn, I always get a "Connection refused. Could you maybe help me find the error?

The Lab-Setup:
                               "External"                                       "Internal"
Host-Network    <------------>  CoTurn VM  <--------------------------------------->  Small SSH
                         192.168.178.100     192.168.99.128                       192.168.99.129

My Call:
```./stunner tcp-scanner -u securetest -p buzzw0rt -s 192.168.178.100:3478 --ports 22 --ip 192.168.99.129 --timeout 60s```

ERRO[0000] error on running HTTP Scan for 192.168.99.129:22: error on establishing control connection: error on establishing a connection to the server: dial tcp 192.168.178.100:3478: connect: connection refused

Debug Log from Stunner:
[debug.log](https://github.com/firefart/stunner/files/14721711/debug.log)

COTURN-Config:
[turnserver.conf.log](https://github.com/firefart/stunner/files/14721737/turnserver.conf.log)

Log from COTURN-server
![TURN-error](https://github.com/firefart/stunner/assets/41263279/43be09f0-0ebb-428f-89a9-1f91caa4fcec)

SSH is reachable from the coturn itself.

Is it maybe a test-lab-setup error?

**Comment by firefart** [comment]
The error message means that you can't reach `192.168.178.100:3478` via TCP. Maybe it only supports UDP or a firewall is restricting access?
What's the output of `stunner info ....` ? Also be sure to use the latest version from github as there where a lot of connection related bugs in previous versions
